//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guflow.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Guflow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not determine the task list to poll on for new tasks when multiple workflows are hosted. Please explicitly pass the task list to begin the execution. .
        /// </summary>
        internal static string Can_not_determine_the_task_list_to_poll_on {
            get {
                return ResourceManager.GetString("Can_not_determine_the_task_list_to_poll_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow item {0} depends on itself.
        /// </summary>
        internal static string Cyclic_dependency {
            get {
                return ResourceManager.GetString("Cyclic_dependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default task list is missing. Please either provide default task list in workflow declaration or pass the one explicitly to begin the execution.
        /// </summary>
        internal static string Default_task_list_is_missing {
            get {
                return ResourceManager.GetString("Default_task_list_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain {0} is decprecated..
        /// </summary>
        internal static string Domain_deprecated {
            get {
                return ResourceManager.GetString("Domain_deprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain is missing..
        /// </summary>
        internal static string Domain_name_missing {
            get {
                return ResourceManager.GetString("Domain_name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain name required..
        /// </summary>
        internal static string Domain_name_required {
            get {
                return ResourceManager.GetString("Domain_name_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity with name {0}, version {1} and positional markerName {2} is already added to workflowClosingActions..
        /// </summary>
        internal static string Duplicate_activity {
            get {
                return ResourceManager.GetString("Duplicate_activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer with name {0} is already added to workflowClosingActions..
        /// </summary>
        internal static string Duplicate_timer {
            get {
                return ResourceManager.GetString("Duplicate_timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version is empty for workflow {0}..
        /// </summary>
        internal static string Empty_version {
            get {
                return ResourceManager.GetString("Empty_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow method {0} has incompatible parameter {1}, which can not be deserialized from source event {2}.
        /// </summary>
        internal static string Invalid_parameter {
            get {
                return ResourceManager.GetString("Invalid_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow method {0} has invalid return type. Only {1} and {2} are allowed as return types..
        /// </summary>
        internal static string Invalid_return_type {
            get {
                return ResourceManager.GetString("Invalid_return_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple workflow methods are found for event {0}. Please provide only one method..
        /// </summary>
        internal static string Multiple_event_methods {
            get {
                return ResourceManager.GetString("Multiple_event_methods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty workflows. Please provide at least one workflow to begin hosting..
        /// </summary>
        internal static string No_workflow_to_host {
            get {
                return ResourceManager.GetString("No_workflow_to_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow type {0} does not derive from {1} class..
        /// </summary>
        internal static string Non_Workflow_type {
            get {
                return ResourceManager.GetString("Non_Workflow_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read startegy is required..
        /// </summary>
        internal static string Read_strategy_required {
            get {
                return ResourceManager.GetString("Read_strategy_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find the schedulable item for {0}..
        /// </summary>
        internal static string Schedulable_item_missing {
            get {
                return ResourceManager.GetString("Schedulable_item_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskList name is required..
        /// </summary>
        internal static string TaskListName_required {
            get {
                return ResourceManager.GetString("TaskListName_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow name {0} and version {1} is already hosted..
        /// </summary>
        internal static string Workflow_already_hosted {
            get {
                return ResourceManager.GetString("Workflow_already_hosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkflowDescriptionAttribute is not applied on workflow {0}..
        /// </summary>
        internal static string Workflow_attribute_missing {
            get {
                return ResourceManager.GetString("Workflow_attribute_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow name {0} and version {1} is deprecated. .
        /// </summary>
        internal static string Workflow_deprecated {
            get {
                return ResourceManager.GetString("Workflow_deprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow execution is already stopped..
        /// </summary>
        internal static string Workflow_execution_already_stopped {
            get {
                return ResourceManager.GetString("Workflow_execution_already_stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow name {0} and version {1} is not hosted..
        /// </summary>
        internal static string Workflow_not_hosted {
            get {
                return ResourceManager.GetString("Workflow_not_hosted", resourceCulture);
            }
        }
    }
}
